#!/bin/bash
export TAG=1.0
export SENTINEL_REPO=${PWD}/sentinel-processing/
export SENTINEL_DATA=/mnt/storage/sentinel1/
export SENTINEL_OUTPUT=/mnt/storage/sentinel1/output
export GRAPH=BasicPreprocess
export USERNAME=rbraswell
export PASSWORD=eurocoolness
export SHP=/mnt/storage/sentinel1/shapefiles/
export START_DATE=2018-04-09
export END_DATE=2018-04-09
export SHAPEFILE=563_344_boundary
export CLIPPED_OUTPUT=/mnt/storage/sentinel1/clipped/
