#!/bin/bash

set -e

eval $(cat gips_creds.sh)
export TAG=${1:-latest}

docker-compose run \
    -v "$HOME/.aws:/root/.aws" \
    -v "$GIPS_DATA:/archive" \
    -v "$GIPS_HOME:/gips" \
    -v "/tmp:/tmp" \
    -v /mnt/storage/gips/SRTM:/root/.snap/auxdata/dem/SRTM\ 1Sec\ HGT/ \
    gips \
    /bin/bash
