#!/bin/bash

set -e

eval $(cat gips_creds.sh)
export TAG=${1:-latest}

docker-compose run \
    -v "$HOME/.aws:/root/.aws" \
    -v "$GIPS_DATA:/export" \
    -v "$GIPS_HOME:/gips" \
    gips \
    /bin/bash
