#!/bin/bash

set -e

eval $(cat gips_creds.sh)
tar xvfz gips_init.tgz

# TODO: Check for version numbers based on minimum system requirements
# TODO: Check that code is executed from top of repo

if ! [ -x "$(command -v docker)" ]; then
  echo 'Error: docker is not installed' >&2
  exit 1
fi

if ! [ -x "$(command -v docker-compose)" ]; then
  echo 'Error: docker-compose is not installed' >&2
  exit 1
fi

./scripts/update "$@"

# TODO: There has got to be a better way to do this
# Using /archive as a way to get two important items out of the container

docker run -v ${GIPS_DATA}:/archive ${OWNER}/gips cp -r gips.egg-info /archive
cp -r ${GIPS_DATA}/gips.egg-info ${GIPS_HOME}/
rm -rf ${GIPS_DATA}/gips.egg-info

docker run -v ${GIPS_DATA}:/archive ${OWNER}/gips cp -r gips/settings.py /archive
cp -r ${GIPS_DATA}/settings.py ${GIPS_HOME}/gips/
rm -rf ${GIPS_DATA}/settings.py

rm -rf ${GIPS_HOME}/gips_init.tgz
