#!/bin/bash

set -e

source init.sh
aws s3 cp s3://${GIPS_S3}/gips_init.tgz ./
tar xvfz gips_init.tgz

# TODO: Check for version numbers based on minimum system requirements
# TODO: Check that code is executed from top of repo

if ! [ -x "$(command -v docker)" ]; then
  echo 'Error: docker is not installed' >&2
  exit 1
fi

if ! [ -x "$(command -v docker-compose)" ]; then
  echo 'Error: docker-compose is not installed' >&2
  exit 1
fi

./scripts/update "$@"

docker run telluslabs/gips cp -r gips.egg-info /export
mv ${GIPS_DATA}/gips.egg-info ${GIPS_HOME}/
