# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(db_index=True, max_length=15)),
                ('asset', models.CharField(db_index=True, max_length=7)),
                ('sensor', models.CharField(db_index=True, max_length=7)),
                ('tile', models.CharField(db_index=True, max_length=15)),
                ('date', models.DateField(db_index=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together=set([('driver', 'asset', 'tile', 'date')]),
        ),
    ]
