# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gips.inventory.dbinv.models


class Migration(migrations.Migration):

    replaces = [('dbinv', '0002_auto_20161107_0840'), ('dbinv', '0003_auto_20161212_2227'), ('dbinv', '0004_auto_20161214_2155'), ('dbinv', '0005_auto_20161215_0809'), ('dbinv', '0006_tranfer_status'), ('dbinv', '0007_auto_20161215_0916'), ('dbinv', '0008_rename_new_status'), ('dbinv', '0009_delete_status'), ('dbinv', '0010_auto_20161215_1132'), ('dbinv', '0011_auto_20161215_1243'), ('dbinv', '0012_auto_20161215_1617'), ('dbinv', '0013_job'), ('dbinv', '0014_auto_20161219_1507'), ('dbinv', '0015_auto_20161219_2219'), ('dbinv', '0016_auto_20161220_1649'), ('dbinv', '0017_remove_result_feature_set'), ('dbinv', '0018_auto_20161221_1617'), ('dbinv', '0019_remove_result_product'), ('dbinv', '0020_auto_20170104_1907'), ('dbinv', '0021_datavariable_category'), ('dbinv', '0022_drop_vector_model')]

    dependencies = [
        ('dbinv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AssetStatusChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(validators=[gips.inventory.dbinv.models.valid_status])),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('asset_link', models.TextField(blank=True, null=True)),
                ('asset', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(max_length=255)),
                ('driver', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('band', models.CharField(max_length=255)),
                ('band_number', models.IntegerField(default=0)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=255)),
                ('spatial', models.TextField()),
                ('temporal', models.TextField()),
                ('status', models.TextField(validators=[gips.inventory.dbinv.models.valid_status])),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbinv.DataVariable')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStatusChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(validators=[gips.inventory.dbinv.models.valid_status])),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('maximum', models.FloatField(blank=True, null=True)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('skew', models.FloatField(blank=True, null=True)),
                ('minimum', models.FloatField(blank=True, null=True)),
                ('sd', models.FloatField(blank=True, null=True)),
                ('fid', models.IntegerField()),
                ('site', models.CharField(max_length=255)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbinv.Job')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.TextField(default='complete', validators=[gips.inventory.dbinv.models.valid_status]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.TextField(default='complete', validators=[gips.inventory.dbinv.models.valid_status]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productstatuschange',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbinv.Product'),
        ),
        migrations.AddField(
            model_name='assetstatuschange',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbinv.Asset'),
        ),
        migrations.AddField(
            model_name='assetdependency',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbinv.Asset'),
        ),
        migrations.AddField(
            model_name='assetdependency',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbinv.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([('job', 'date', 'site')]),
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together=set([('site', 'variable', 'spatial', 'temporal')]),
        ),
        migrations.AlterUniqueTogether(
            name='assetdependency',
            unique_together=set([('product', 'asset')]),
        ),
    ]
