# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gips.inventory.dbinv.models



def link_status(apps, schema_editor):
    Asset = apps.get_model('dbinv', 'Asset')
    for asset in Asset.objects.all():
        asset.new_status = asset.status.status
        asset.save()
    Product = apps.get_model('dbinv', 'Product')
    for product in Product.objects.all():
        product.new_status = product.status.status
        product.save()
        

class Migration(migrations.Migration):

    replaces = [('dbinv', '0002_auto_20161107_0840'), ('dbinv', '0003_auto_20161212_2227'), ('dbinv', '0004_auto_20161214_2155'), ('dbinv', '0005_auto_20161215_0809'), ('dbinv', '0006_tranfer_status'), ('dbinv', '0007_auto_20161215_0916'), ('dbinv', '0008_rename_new_status'), ('dbinv', '0009_delete_status'), ('dbinv', '0010_auto_20161215_1132'), ('dbinv', '0011_auto_20161215_1243'), ('dbinv', '0012_auto_20161215_1617'), ('dbinv', '0013_job'), ('dbinv', '0014_auto_20161219_1507'), ('dbinv', '0015_auto_20161219_2219'), ('dbinv', '0016_auto_20161220_1649'), ('dbinv', '0017_remove_result_feature_set'), ('dbinv', '0018_auto_20161221_1617'), ('dbinv', '0019_remove_result_product'), ('dbinv', '0020_auto_20170104_1907'), ('dbinv', '0021_datavariable_category'), ('dbinv', '0022_drop_vector_model')]

    dependencies = [
        ('dbinv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dbinv.Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dbinv.Status'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DataVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('driver', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('band', models.CharField(max_length=255)),
                ('band_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_set', models.CharField(max_length=255)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('maximum', models.FloatField(blank=True, null=True)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('skew', models.FloatField(blank=True, null=True)),
                ('minimum', models.FloatField(blank=True, null=True)),
                ('sd', models.FloatField(blank=True, null=True)),
                ('fid', models.IntegerField()),
                ('site', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbinv.DataVariable')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([('feature_set', 'date', 'product', 'site')]),
        ),
        migrations.AddField(
            model_name='asset',
            name='new_status',
            field=models.TextField(default='complete', validators=[gips.inventory.dbinv.models.valid_status]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='new_status',
            field=models.TextField(default='complete', validators=[gips.inventory.dbinv.models.valid_status]),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=link_status,
        ),
        migrations.RemoveField(
            model_name='asset',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RenameField(
            model_name='Product',
            old_name='new_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='Asset',
            old_name='new_status',
            new_name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.CreateModel(
            name='AssetDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbinv.Asset')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbinv.Product')),
            ],
        ),
        migrations.CreateModel(
            name='AssetStatusChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(validators=[gips.inventory.dbinv.models.valid_status])),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbinv.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStatusChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(validators=[gips.inventory.dbinv.models.valid_status])),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbinv.Asset')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='productstatuschange',
            unique_together=set([('product', 'status')]),
        ),
        migrations.AlterUniqueTogether(
            name='assetstatuschange',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='assetdependency',
            unique_together=set([('product', 'asset')]),
        ),
        migrations.AlterField(
            model_name='productstatuschange',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbinv.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='productstatuschange',
            unique_together=set([]),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=255)),
                ('spatial', models.TextField()),
                ('temporal', models.TextField()),
                ('status', models.TextField(validators=[gips.inventory.dbinv.models.valid_status])),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbinv.DataVariable')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together=set([('site', 'variable', 'spatial', 'temporal')]),
        ),
        migrations.AddField(
            model_name='result',
            name='job',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dbinv.Job'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='result',
            name='feature_set',
        ),
        migrations.RemoveField(
            model_name='result',
            name='product',
        ),
        migrations.RemoveField(
            model_name='result',
            name='vector',
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([('job', 'date', 'site')]),
        ),
        migrations.AddField(
            model_name='datavariable',
            name='asset',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datavariable',
            name='asset_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datavariable',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datavariable',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
