# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-17 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbinv', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('driver', 'product', 'sensor', 'tile', 'date')]),
        ),
    ]
