# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gips.inventory.dbinv.models


class Migration(migrations.Migration):

    replaces = [('dbinv', '0003_auto_20170224_0432'), ('dbinv', '0004_auto_20170227_0817'), ('dbinv', '0005_auto_20170301_0932'), ('dbinv', '0006_auto_20170306_1002')]

    dependencies = [
        ('dbinv', '0002_datahandler'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='sched_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sched_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetstatuschange',
            name='sched_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productstatuschange',
            name='sched_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='shaid',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([('job', 'date', 'shaid')]),
        ),
        migrations.CreateModel(
            name='JobStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(validators=[gips.inventory.dbinv.models.valid_status])),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('sched_id', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbinv.Job')),
            ],
        ),
        migrations.CreateModel(
            name='PostProcessJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('args', models.TextField()),
                ('status', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('sched_id', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbinv.Job')),
            ],
        ),
    ]
