# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-14 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbinv', '0003_auto_20161212_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='vector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbinv.Vector'),
        ),
    ]
