# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-04 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbinv', '0003_auto_20170224_0432_squashed_0006_auto_20170306_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='fid',
        ),
        migrations.AlterUniqueTogether(
            name='postprocessjobs',
            unique_together=set([('job', 'args')]),
        ),
    ]
