# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbinv', '0003_auto_20170224_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetstatuschange',
            name='sched_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productstatuschange',
            name='sched_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
