# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-15 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import gips.inventory.dbinv.models


class Migration(migrations.Migration):

    dependencies = [
        ('dbinv', '0004_auto_20161214_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='new_status',
            field=models.TextField(default='complete', validators=[gips.inventory.dbinv.models.valid_status]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='new_status',
            field=models.TextField(default='complete', validators=[gips.inventory.dbinv.models.valid_status]),
            preserve_default=False,
        ),
    ]
