# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbinv', '0004_auto_20170404_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='datavariable',
            name='latency',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='datavariable',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
