# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-08 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbinv', '0005_auto_20170425_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datavariable',
            old_name='unit',
            new_name='units',
        ),
    ]
