# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-15 09:00
from __future__ import unicode_literals

from django.db import migrations

def link_status(apps, schema_editor):
    Asset = apps.get_model('dbinv', 'Asset')
    for asset in Asset.objects.all():
        asset.new_status = asset.status.status
        asset.save()
    Product = apps.get_model('dbinv', 'Product')
    for product in Product.objects.all():
        product.new_status = product.status.status
        product.save()
        
class Migration(migrations.Migration):

    dependencies = [
        ('dbinv', '0005_auto_20161215_0809'),
    ]

    operations = [
        migrations.RunPython(link_status)
    ]
