# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-15 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbinv', '0006_tranfer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
