# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-15 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbinv', '0007_auto_20161215_0916'),
    ]

    operations = [
        migrations.RenameField('Product', 'new_status', 'status'),
        migrations.RenameField('Asset', 'new_status', 'status')
    ]
