# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-01 19:59
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbinv', '0007_auto_20171201_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geometry',
            name='wkt',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
