# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-15 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbinv', '0008_rename_new_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
