# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-15 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbinv', '0010_auto_20161215_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstatuschange',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbinv.Product'),
        ),
    ]
