# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 12:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import gips.inventory.dbinv.models


class Migration(migrations.Migration):

    dependencies = [
        ('dbinv', '0012_auto_20161215_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=255)),
                ('spatial', django.contrib.postgres.fields.hstore.HStoreField()),
                ('temporal', django.contrib.postgres.fields.hstore.HStoreField()),
                ('status', models.TextField(validators=[gips.inventory.dbinv.models.valid_status])),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbinv.DataVariable')),
            ],
        ),
    ]
