# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbinv', '0013_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='spatial',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='temporal',
            field=models.TextField(),
        ),
    ]
