# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbinv', '0014_auto_20161219_1507'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='job',
            unique_together=set([('site', 'variable', 'spatial', 'temporal')]),
        ),
    ]
