# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-20 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbinv', '0015_auto_20161219_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='job',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dbinv.Job'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([('job', 'date', 'product', 'site')]),
        ),
    ]
