# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbinv', '0017_remove_result_feature_set'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([('job', 'date', 'site')]),
        ),
    ]
