# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbinv', '0019_remove_result_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='datavariable',
            name='asset',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datavariable',
            name='asset_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datavariable',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
