# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbinv', '0020_auto_20170104_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='datavariable',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
