# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbinv', '0021_datavariable_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vector',
        ),
        migrations.RemoveField(
            model_name='result',
            name='vector',
        ),
    ]
